receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 30s
    timeout: 5s

  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu: {}
      memory: {}
      load: {}
      network: {}
      disk: {}
      filesystem: {}

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  resourcedetection:
    detectors: [system]
    system:
      hostname_sources: [os]
    timeout: 5s

  transform:
    metric_statements:
      - context: resource
        statements:
          - set(attributes["host.name"], "fedora")
          - set(attributes["service.name"], "fedora-system")

exporters:
  otlp:
    endpoint: "ingest.us.signoz.cloud:443"
    tls:
      insecure: false
    headers:
      "signoz-access-token": "a2442dc2-80db-4b78-83ed-41fa2e8e76de"
    compression: gzip
    timeout: 30s

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [otlp]
    
    metrics:
      receivers: [otlp, docker_stats, hostmetrics]
      processors: [resourcedetection, transform, batch]
      exporters: [otlp]
    
    logs:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [otlp]